AWSTemplateFormatVersion: '2010-09-09'
Description: "codedeploy"

Parameters:
  ApplicationName:
    Type: String

  S3BucketName:
    Type: String
  S3BucketAccessKey:
    Type: String

  EC2TagKey:
    Type: String
  EC2TagValue:
    Type: String

  CodeDeployServiceRoleArn:
    Type: String

Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      ComputePlatform: Server

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties: 
      ApplicationName: !Ref CodeDeployApplication
      Ec2TagFilters: 
        - Key: !Ref EC2TagKey 
          Value: !Ref EC2TagValue
          Type: KEY_AND_VALUE
      ServiceRoleArn: !Ref CodeDeployServiceRoleArn
      Deployment:
        IgnoreApplicationStopFailures: true
        Revision:
          RevisionType: S3
          S3Location: 
            Bucket: !Ref S3BucketName
            Key: !Ref S3BucketAccessKey
            BundleType: Zip
